################################################################################

- date: January 5, 2025 
  title: Second Sunday after Christmas
  mp3: true
  bulletin: false
- date: January 12, 2025 
  title: First Sunday after the Epiphany
  mp3: false
  bulletin: false
- date: January 19, 2025 
  title: Second Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 26, 2025 
  title: Third Sunday after the Epiphany
  mp3: true
  bulletin: false

################################################################################

- date: February 2, 2025 
  title: Fourth Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: February 9, 2025
  title: Fifth Sunday after the Epiphany
  mp3: false
  bulletin: false
- date: February 16, 2025
  title: Sixth Sunday after the Epiphany
  mp3: false
  bulletin: false
- date: February 23, 2025
  title: Seventh Sunday after the Epiphany
  mp3: true
  bulletin: false

################################################################################

- date: March 2, 2025
  title: Last Sunday after Epiphany
  mp3: true
  bulletin: false
- date: March 9, 2025
  title: First Sunday in Lent
  mp3: true
  bulletin: false
- date: March 16, 2025
  title: Second Sunday in Lent
  mp3: true
  bulletin: false
- date: March 23, 2025
  title: Third Sunday in Lent
  mp3: true
  bulletin: false
- date: March 30, 2025
  title: Fourth Sunday in Lent
  mp3: true
  bulletin: false

################################################################################

- date: April 6, 2025
  title: Fifth Sunday in Lent
  mp3: true
  bulletin: false
- date: April 13, 2025
  title: Palm Sunday
  mp3: true
  bulletin: false
- date: April 20, 2025
  title: Easter Sunday
  mp3: true
  bulletin: false
- date: April 27, 2025
  title: Second Sunday of Easter
  mp3: false
  bulletin: false

################################################################################

- date: May 4, 2025
  title: Third Sunday of Easter
  mp3: false
  bulletin: false
- date: May 11, 2025
  title: Fourth Sunday of Easter
  mp3: false
  bulletin: false
- date: May 18, 2025
  title: Fifth Sunday of Easter
  mp3: true
  bulletin: false
- date: May 25, 2025
  title: Sixth Sunday of Easter
  mp3: true
  bulletin: false

################################################################################

- date: June 1, 2025
  title: Seventh Sunday of Easter
  mp3: true
  bulletin: false
- date: June 8, 2025
  title: Pentecost
  mp3: false
  bulletin: false
- date: June 15, 2025
  title: Trinity Sunday
  mp3: true
  bulletin: false
- date: June 22, 2025
  title: Second Sunday after Pentecost
  mp3: true
  bulletin: false
- date: June 29, 2025
  title: Third Sunday after Pentecost
  mp3: true
  bulletin: false

################################################################################

- date: July 6, 2025
  title: Fourth Sunday after Pentecost
  mp3: false
  bulletin: false
- date: July 13, 2025
  title: Fifth Sunday after Pentecost
  mp3: false
  bulletin: false
- date: July 20, 2025
  title: Sixth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: July 27, 2025
  title: Seventh Sunday after Pentecost
  mp3: true
  bulletin: false

#################################################################################

- date: August 3, 2025
  title: Eighth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: August 10, 2025
  title: Ninth Sunday after Pentecost
  mp3: false
  bulletin: false
- date: August 17, 2025
  title: Tenth Sunday after Pentecost
  mp3: false
  bulletin: false
- date: August 24, 2025
  title: Eleventh Sunday after Pentecost
  mp3: true
  bulletin: false
- date: August 31, 2025
  title: Twelfth Sunday after Pentecost
  mp3: true
  bulletin: false

################################################################################

- date: September 7, 2025
  title: Thirteenth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: September 14, 2025
  title: Fourteenth Sunday after Pentecost
  mp3: false
  bulletin: false
- date: September 21, 2025
  title: Fifteenth Sunday after Pentecost
  mp3: false
  bulletin: false
- date: September 28, 2025
  title: Sixteenth Sunday after Pentecost
  mp3: false
  bulletin: false 

################################################################################

- date: October 5, 2025
  title: Seventeenth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: October 12, 2025
  title: Eighteenth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: October 19, 2025
  title: Nineteenth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: October 26, 2025
  title: Twentieth Sunday after Pentecost
  mp3: false
  bulletin: false

################################################################################

- date: November 2, 2025
  title: Twenty-first Sunday after Pentecost
  mp3: false
  bulletin: false
- date: November 9, 2025
  title: Twenty-second Sunday after Pentecost
  mp3: true
  bulletin: false
- date: November 16, 2025
  title: Twenty-third Sunday after Pentecost
  mp3: true
  bulletin: false
- date: November 23, 2025
  title: Christ the King Sunday
  mp3: true
  bulletin: false
- date: November 30, 2025
  title: First Sunday of Advent
  mp3: false
  bulletin: false

################################################################################

- date: December 7, 2025
  title: Second Sunday of Advent
  mp3: false
  bulletin: false
- date: December 14, 2025
  title: Third Sunday of Advent
  mp3: false
  bulletin: false
- date: December 21, 2025
  title: Fourth Sunday of Advent
  mp3: true
  bulletin: false