################################################################################

- date: January 11, 2026
  title: First Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 18, 2026
  title: Second Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 25, 2026
  title: Third Sunday after the Epiphany
  mp3: true
  bulletin: false

################################################################################

- date: February 1, 2026
  title: Fourth Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: February 8, 2026
  title: Fifth Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: February 15, 2026
  title: Last Sunday after Epiphany
  mp3: true
  bulletin: false